### ISSUE TITLE
crash each time I open a calc

### ISSUE THREAD

**Issue by vivienprouvot** [framasoft/framacalc#11]
Hi / bonjour, 
I'm using framacalc and I'm very glad, your tool is amazing :)

unfortunatly, I put SUM(C3:C999999999999999) in a the C3 cells. 
So the calc is stuck with the message "référence circulaire, C3 referenced by C3"
-> I don't know if I can recover old version (datas I hope we didn't loose)
-> I don't know if the problem occured from the quantity of 9's I put
-> or if the problem occured due to the C3 calling itself. 
Link is : https://lite.framacalc.org/9jn4-wbht018j1p

Anyway thank you by advance for your help,
We can continue in french if prefered.

Vivien

**Comment by vivienprouvot** [comment]
I tried to reproduce the problem with success : it comes from the amount of 9s I put behind. 
I actually wanted to write (C1:CInfinite) but couldn't find a way to do so.

**Comment by ghost** [comment]
On Framacalc we offer a history that allows you to restore an earlier version of the calc (thanks to https://framagit.org/framasoft/ert):
You can access to your history on the tab “Anciennes révisions”.

(I repared your calc)

For more generic problems with Ethercalc (such as being blocked by this kind of loop) it is best to open a issue on the official repository https://github.com/audreyt/ethercalc
We don't develop it.
